# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 854943b8c2c1520a58abd73d51dd0e38baadd2941dda356d26eb5006cebe5b6e9ea91846148b0bcd1b0e231202a26901220f321a64e19e65f9a7553ded16b9f3

test:
  secret_key_base: d532ec80a8ad9beab4b55c00f7bc736cb7f8afeff9d549acf661d567922f84ff406cb3c59764a6ca1bfb2f681aed2f81afb615c89349c7868fecea31aa620f6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
